
FROM node:18 AS build  

WORKDIR /app  

COPY package*.json ./   

RUN npm install  

RUN cd node_modules/pdfmake && node build-vfs.js "../../fonts" "./build/vfs_font.js" 

COPY . .  

RUN npm run build  

FROM nginx:alpine  

COPY --from=build /app/build /usr/share/nginx/html  

EXPOSE 80  

CMD ["nginx", "-g", "daemon off;"]