version: '3.8'  

services:  
  frontend:  
    build:  
      context: ./client 
      dockerfile: Dockerfile  
    ports:  
      - "3000:80" 
    env_file:  
      - ./client/.env 

  backend:  
    build:  
      context: ./server 
      dockerfile: Dockerfile  
    ports:  
      - "3001:3000"
    env_file:  
      - E:\готовые проекты\myseeker\job-senta\server\.env  

  db:  
    image: postgres:14  
    environment:  
      POSTGRES_USER: ${DB_USER}       
      POSTGRES_PASSWORD: ${DB_PASSWORD}   
      POSTGRES_DB: ${DB_NAME}  
    ports:  
      - "5432:5432"