export const skilsData = [
    { value: 'HTML', label: 'HTML' },
    { value: 'CSS', label: 'CSS' },
    { value: 'Java Script', label: 'Java Script' },
    { value: 'React.js', label: 'React.js' },
    { value: 'Type Script', label: 'Type Script' },
    { value: 'Git1', label: 'Git' },
    { value: 'Git2', label: 'Git' },
    { value: 'Git3', label: 'Git' },
    { value: 'Git4', label: 'Git' },
    { value: 'Git5', label: 'Git' },
    { value: 'Git6', label: 'Git' },
    { value: 'Git7', label: 'Git' },
    { value: 'Git8', label: 'Git' },
  ];