export const skillsData = [
  { value: "3D Animation", label: "3D Animation" },
  { value: "3D Modeling", label: "3D Modeling" },
  { value: "3D Printing", label: "3D Printing" },
  { value: "5S Methodology", label: "5S Methodology" },
  { value: "A/B Testing", label: "A/B Testing" },
  { value: "AC/DC Motors", label: "AC/DC Motors" },
  { value: "AI in Healthcare", label: "AI in Healthcare" },
  {
    value: "AML (Anti-Money Laundering)",
    label: "AML (Anti-Money Laundering)",
  },
  { value: "AML Compliance", label: "AML Compliance" },
  { value: "AML Screening", label: "AML Screening" },
  { value: "AP Exam Instruction", label: "AP Exam Instruction" },
  { value: "API Integration", label: "API Integration" },
  { value: "API Security", label: "API Security" },
  { value: "AWS (Amazon Web Services)", label: "AWS (Amazon Web Services)" },
  { value: "Access Control Policy", label: "Access Control Policy" },
  { value: "Access Control Systems", label: "Access Control Systems" },
  { value: "Account Management", label: "Account Management" },
  {
    value: "Account-Based Marketing (ABM)",
    label: "Account-Based Marketing (ABM)",
  },
  { value: "Accounting Standards", label: "Accounting Standards" },
  { value: "Accounts Payable", label: "Accounts Payable" },
  { value: "Accounts Receivable", label: "Accounts Receivable" },
  {
    value: "Active Directory Management",
    label: "Active Directory Management",
  },
  { value: "ActiveCampaign", label: "ActiveCampaign" },
  { value: "Actuarial Analysis", label: "Actuarial Analysis" },
  { value: "Actuarial Forecasting", label: "Actuarial Forecasting" },
  { value: "Actuarial Modeling", label: "Actuarial Modeling" },
  { value: "Adaptability", label: "Adaptability" },
  { value: "Adobe Illustrator", label: "Adobe Illustrator" },
  { value: "Adobe Photoshop", label: "Adobe Photoshop" },
  { value: "Adult Education", label: "Adult Education" },
  {
    value: "Advanced Threat Protection (ATP)",
    label: "Advanced Threat Protection (ATP)",
  },
  {
    value: "Advocacy Campaign Management",
    label: "Advocacy Campaign Management",
  },
  { value: "Affiliate Marketing", label: "Affiliate Marketing" },
  { value: "Agile Methodologies", label: "Agile Methodologies" },
  { value: "Aircraft Maintenance", label: "Aircraft Maintenance" },
  { value: "Airport Management", label: "Airport Management" },
  { value: "Alternative Investments", label: "Alternative Investments" },
  { value: "Analog Circuit Design", label: "Analog Circuit Design" },
  { value: "Android Development", label: "Android Development" },
  { value: "Animation", label: "Animation" },
  { value: "Anomaly Detection", label: "Anomaly Detection" },
  { value: "Ansible", label: "Ansible" },
  { value: "Anti-Phishing Strategies", label: "Anti-Phishing Strategies" },
  { value: "Application Security", label: "Application Security" },
  {
    value: "Architectural Site Planning",
    label: "Architectural Site Planning",
  },
  { value: "Archiving", label: "Archiving" },
  { value: "Art Direction", label: "Art Direction" },
  { value: "Art Handling", label: "Art Handling" },
  { value: "Art Therapy", label: "Art Therapy" },
  { value: "Artifact Preservation", label: "Artifact Preservation" },
  { value: "Artificial Intelligence", label: "Artificial Intelligence" },
  { value: "Artwork Restoration", label: "Artwork Restoration" },
  { value: "Asana", label: "Asana" },
  { value: "Assembly Line Optimization", label: "Assembly Line Optimization" },
  { value: "Assessment Design", label: "Assessment Design" },
  { value: "Asset Management", label: "Asset Management" },
  { value: "Asset Protection", label: "Asset Protection" },
  { value: "Asset Tracing", label: "Asset Tracing" },
  { value: "Attention to Detail", label: "Attention to Detail" },
  { value: "Audio Editing", label: "Audio Editing" },
  { value: "Audit Management", label: "Audit Management" },
  { value: "Audit Readiness", label: "Audit Readiness" },
  { value: "Auditing", label: "Auditing" },
  { value: "Augmented Reality", label: "Augmented Reality" },
  { value: "AutoCAD", label: "AutoCAD" },
  { value: "Automotive Repair", label: "Automotive Repair" },
  { value: "Autonomous Vehicle Systems", label: "Autonomous Vehicle Systems" },
  { value: "Avionics", label: "Avionics" },
  { value: "Azure", label: "Azure" },
  { value: "Backend Development", label: "Backend Development" },
  { value: "Background Checks", label: "Background Checks" },
  { value: "Background Investigation", label: "Background Investigation" },
  { value: "Backup and Recovery", label: "Backup and Recovery" },
  { value: "Banking Operations", label: "Banking Operations" },
  { value: "Barcode Scanning", label: "Barcode Scanning" },
  { value: "Basecamp", label: "Basecamp" },
  { value: "Behavioral Analysis", label: "Behavioral Analysis" },
  {
    value: "Behavioral Health Counseling",
    label: "Behavioral Health Counseling",
  },
  { value: "Behavioral Therapy", label: "Behavioral Therapy" },
  { value: "Benefits Administration", label: "Benefits Administration" },
  { value: "Big Data Management", label: "Big Data Management" },
  { value: "BigQuery", label: "BigQuery" },
  { value: "Billing and Coding", label: "Billing and Coding" },
  { value: "Biodiversity Management", label: "Biodiversity Management" },
  { value: "Bioinformatics", label: "Bioinformatics" },
  { value: "Biomass", label: "Biomass" },
  { value: "Biometric Authentication", label: "Biometric Authentication" },
  { value: "Biometric Data Analysis", label: "Biometric Data Analysis" },
  { value: "Biostatistics", label: "Biostatistics" },
  { value: "Blockchain", label: "Blockchain" },
  { value: "Blue Teaming", label: "Blue Teaming" },
  { value: "Blueprint Reading", label: "Blueprint Reading" },
  { value: "Book Acquisition", label: "Book Acquisition" },
  { value: "Bot Mitigation", label: "Bot Mitigation" },
  { value: "Brand Awareness", label: "Brand Awareness" },
  { value: "Brand Management", label: "Brand Management" },
  { value: "Brand Storytelling", label: "Brand Storytelling" },
  { value: "Brand Strategy Development", label: "Brand Strategy Development" },
  { value: "Budget Forecasting", label: "Budget Forecasting" },
  { value: "Budgeting", label: "Budgeting" },
  {
    value: "Building Information Modeling (BIM)",
    label: "Building Information Modeling (BIM)",
  },
  { value: "Building Permits", label: "Building Permits" },
  { value: "Business Case Development", label: "Business Case Development" },
  {
    value: "Business Continuity Planning",
    label: "Business Continuity Planning",
  },
  { value: "Business Development", label: "Business Development" },
  { value: "Business Intelligence", label: "Business Intelligence" },
  {
    value: "Business Process Reengineering (BPR)",
    label: "Business Process Reengineering (BPR)",
  },
  { value: "C#", label: "C#" },
  { value: "C++", label: "C++" },
  {
    value: "CAD (Computer-Aided Design)",
    label: "CAD (Computer-Aided Design)",
  },
  { value: "CAD/CAM Integration", label: "CAD/CAM Integration" },
  {
    value: "CAE (Computer-Aided Engineering)",
    label: "CAE (Computer-Aided Engineering)",
  },
  {
    value: "CAM (Computer-Aided Manufacturing)",
    label: "CAM (Computer-Aided Manufacturing)",
  },
  { value: "CATIA", label: "CATIA" },
  { value: "CNC Machining", label: "CNC Machining" },
  { value: "CNC Programming", label: "CNC Programming" },
  { value: "CRM Analytics", label: "CRM Analytics" },
  { value: "CRM Software", label: "CRM Software" },
  { value: "Campaign Management", label: "Campaign Management" },
  { value: "Campaign Strategy", label: "Campaign Strategy" },
  { value: "Cap Table Management", label: "Cap Table Management" },
  { value: "Capacity Planning", label: "Capacity Planning" },
  { value: "Capital Budgeting", label: "Capital Budgeting" },
  { value: "Carbon Footprint Analysis", label: "Carbon Footprint Analysis" },
  { value: "Cargo Insurance", label: "Cargo Insurance" },
  { value: "Caricature", label: "Caricature" },
  { value: "Carpentry", label: "Carpentry" },
  { value: "Cartographic Design", label: "Cartographic Design" },
  { value: "Cartography", label: "Cartography" },
  { value: "Case Coordination", label: "Case Coordination" },
  { value: "Case Management", label: "Case Management" },
  { value: "Cash Flow Management", label: "Cash Flow Management" },
  { value: "Casualty Insurance", label: "Casualty Insurance" },
  { value: "Cataloging", label: "Cataloging" },
  { value: "Category Management", label: "Category Management" },
  { value: "Change Management", label: "Change Management" },
  { value: "Channel Marketing", label: "Channel Marketing" },
  { value: "Channel Sales", label: "Channel Sales" },
  { value: "Charitable Event Planning", label: "Charitable Event Planning" },
  { value: "Child Development", label: "Child Development" },
  { value: "Chiropractic", label: "Chiropractic" },
  { value: "Churn Analysis", label: "Churn Analysis" },
  { value: "Cinematography", label: "Cinematography" },
  { value: "Circuit Board Layout", label: "Circuit Board Layout" },
  { value: "Civil Engineering", label: "Civil Engineering" },
  { value: "Claims Adjudication", label: "Claims Adjudication" },
  { value: "Claims Adjusting", label: "Claims Adjusting" },
  { value: "Claims Appeals Processing", label: "Claims Appeals Processing" },
  { value: "Claims Denial Management", label: "Claims Denial Management" },
  { value: "Claims Fraud Detection", label: "Claims Fraud Detection" },
  { value: "Claims Processing", label: "Claims Processing" },
  { value: "Classroom Management", label: "Classroom Management" },
  {
    value: "Classroom Technology Integration",
    label: "Classroom Technology Integration",
  },
  { value: "Client Relations", label: "Client Relations" },
  { value: "Client Security Briefings", label: "Client Security Briefings" },
  { value: "Climate Change Adaptation", label: "Climate Change Adaptation" },
  { value: "Clinical Data Management", label: "Clinical Data Management" },
  { value: "Clinical Trials", label: "Clinical Trials" },
  { value: "Clinical Workflow Analysis", label: "Clinical Workflow Analysis" },
  { value: "Cloud Computing", label: "Cloud Computing" },
  { value: "Cloud Security", label: "Cloud Security" },
  {
    value: "Cloud Security Architecture",
    label: "Cloud Security Architecture",
  },
  { value: "Co-Insurance Analysis", label: "Co-Insurance Analysis" },
  { value: "Code Review", label: "Code Review" },
  {
    value: "Cognitive Behavioral Therapy (CBT)",
    label: "Cognitive Behavioral Therapy (CBT)",
  },
  { value: "Cold Calling", label: "Cold Calling" },
  { value: "Collection Management", label: "Collection Management" },
  {
    value: "College Admissions Counseling",
    label: "College Admissions Counseling",
  },
  { value: "College Essay Coaching", label: "College Essay Coaching" },
  {
    value: "Command Line Interface (CLI)",
    label: "Command Line Interface (CLI)",
  },
  { value: "Commission Management", label: "Commission Management" },
  { value: "Communication", label: "Communication" },
  { value: "Community Building", label: "Community Building" },
  { value: "Community Development", label: "Community Development" },
  { value: "Community Engagement", label: "Community Engagement" },
  {
    value: "Community Engagement Strategy",
    label: "Community Engagement Strategy",
  },
  { value: "Community Outreach", label: "Community Outreach" },
  { value: "Community Relations", label: "Community Relations" },
  { value: "Compensation Analysis", label: "Compensation Analysis" },
  { value: "Compensation Benchmarking", label: "Compensation Benchmarking" },
  { value: "Compensation and Benefits", label: "Compensation and Benefits" },
  { value: "Competitive Analysis", label: "Competitive Analysis" },
  {
    value: "Competitive Differentiation",
    label: "Competitive Differentiation",
  },
  { value: "Competitive Pricing", label: "Competitive Pricing" },
  { value: "Compliance Management", label: "Compliance Management" },
  { value: "Compliance Testing", label: "Compliance Testing" },
  { value: "Computer Vision", label: "Computer Vision" },
  { value: "Concrete Pouring", label: "Concrete Pouring" },
  { value: "Confined Space Safety", label: "Confined Space Safety" },
  { value: "Conflict Management", label: "Conflict Management" },
  { value: "Conflict Mediation", label: "Conflict Mediation" },
  { value: "Conflict Resolution", label: "Conflict Resolution" },
  { value: "Confluence", label: "Confluence" },
  { value: "Consolidation Accounting", label: "Consolidation Accounting" },
  { value: "Construction Estimation", label: "Construction Estimation" },
  { value: "Construction Management", label: "Construction Management" },
  { value: "Construction Safety", label: "Construction Safety" },
  { value: "Construction Scheduling", label: "Construction Scheduling" },
  { value: "Containerization", label: "Containerization" },
  { value: "Content Creation", label: "Content Creation" },
  { value: "Content Curation", label: "Content Curation" },
  { value: "Content Personalization", label: "Content Personalization" },
  { value: "Content Strategy", label: "Content Strategy" },
  { value: "Continuous Deployment (CD)", label: "Continuous Deployment (CD)" },
  {
    value: "Continuous Integration (CI)",
    label: "Continuous Integration (CI)",
  },
  {
    value: "Continuous Learning Programs",
    label: "Continuous Learning Programs",
  },
  { value: "Continuous Monitoring", label: "Continuous Monitoring" },
  { value: "Contract Negotiation", label: "Contract Negotiation" },
  { value: "Control Panel Design", label: "Control Panel Design" },
  {
    value: "Conversion Rate Optimization",
    label: "Conversion Rate Optimization",
  },
  { value: "Convertible Debt", label: "Convertible Debt" },
  { value: "Copy Editing", label: "Copy Editing" },
  { value: "Copywriting", label: "Copywriting" },
  { value: "Corporate Culture", label: "Corporate Culture" },
  { value: "Corporate Governance", label: "Corporate Governance" },
  { value: "Corporate Philanthropy", label: "Corporate Philanthropy" },
  { value: "Corporate Security", label: "Corporate Security" },
  {
    value: "Corporate Social Responsibility",
    label: "Corporate Social Responsibility",
  },
  { value: "Corrosion Engineering", label: "Corrosion Engineering" },
  { value: "Cost Accounting", label: "Cost Accounting" },
  { value: "Cost Control", label: "Cost Control" },
  { value: "Cost Optimization", label: "Cost Optimization" },
  { value: "Counseling", label: "Counseling" },
  { value: "Creativity", label: "Creativity" },
  { value: "Credit Analysis", label: "Credit Analysis" },
  { value: "Credit Card Authorization", label: "Credit Card Authorization" },
  { value: "Credit Risk Management", label: "Credit Risk Management" },
  { value: "Credit Underwriting", label: "Credit Underwriting" },
  { value: "Crisis Intervention", label: "Crisis Intervention" },
  { value: "Crisis Management", label: "Crisis Management" },
  { value: "Crisis Response", label: "Crisis Response" },
  { value: "Critical Thinking", label: "Critical Thinking" },
  { value: "Cross-Selling", label: "Cross-Selling" },
  {
    value: "Cultural Diversity Training",
    label: "Cultural Diversity Training",
  },
  {
    value: "Cultural Sensitivity Training",
    label: "Cultural Sensitivity Training",
  },
  { value: "Curriculum Development", label: "Curriculum Development" },
  { value: "Curriculum Mapping", label: "Curriculum Mapping" },
  { value: "Customer Account Renewal", label: "Customer Account Renewal" },
  { value: "Customer Advocacy", label: "Customer Advocacy" },
  { value: "Customer Feedback Analysis", label: "Customer Feedback Analysis" },
  {
    value: "Customer Feedback Collection",
    label: "Customer Feedback Collection",
  },
  { value: "Customer Journey Mapping", label: "Customer Journey Mapping" },
  { value: "Customer Pitching", label: "Customer Pitching" },
  { value: "Customer Retention", label: "Customer Retention" },
  {
    value: "Customer Retention Strategies",
    label: "Customer Retention Strategies",
  },
  {
    value: "Customer Satisfaction Analysis",
    label: "Customer Satisfaction Analysis",
  },
  { value: "Customer Segmentation", label: "Customer Segmentation" },
  { value: "Customer Service", label: "Customer Service" },
  {
    value: "Customer Success Management",
    label: "Customer Success Management",
  },
  { value: "Customer Success Strategy", label: "Customer Success Strategy" },
  { value: "Customer Support Software", label: "Customer Support Software" },
  { value: "Customs Regulations", label: "Customs Regulations" },
  { value: "Cyber Forensics", label: "Cyber Forensics" },
  { value: "Cyber Risk Management", label: "Cyber Risk Management" },
  { value: "Cyber Threat Intelligence", label: "Cyber Threat Intelligence" },
  { value: "Cybersecurity", label: "Cybersecurity" },
  { value: "DNA Sequencing", label: "DNA Sequencing" },
  { value: "Data Analysis", label: "Data Analysis" },
  { value: "Data Breach Prevention", label: "Data Breach Prevention" },
  { value: "Data Center Operations", label: "Data Center Operations" },
  { value: "Data Classification", label: "Data Classification" },
  { value: "Data Encryption", label: "Data Encryption" },
  { value: "Data Encryption Standards", label: "Data Encryption Standards" },
  { value: "Data Governance", label: "Data Governance" },
  { value: "Data Integration", label: "Data Integration" },
  { value: "Data Integrity", label: "Data Integrity" },
  { value: "Data Labeling", label: "Data Labeling" },
  { value: "Data Lake Design", label: "Data Lake Design" },
  { value: "Data Leak Prevention", label: "Data Leak Prevention" },
  { value: "Data Mining", label: "Data Mining" },
  { value: "Data Pipeline Development", label: "Data Pipeline Development" },
  { value: "Data Privacy Compliance", label: "Data Privacy Compliance" },
  { value: "Data Quality", label: "Data Quality" },
  { value: "Data Retention Policy", label: "Data Retention Policy" },
  { value: "Data Visualization", label: "Data Visualization" },
  { value: "Data Warehousing", label: "Data Warehousing" },
  { value: "Database Design", label: "Database Design" },
  { value: "Database Management", label: "Database Management" },
  {
    value: "Database Performance Tuning",
    label: "Database Performance Tuning",
  },
  { value: "Database Security", label: "Database Security" },
  { value: "Debt Collection", label: "Debt Collection" },
  { value: "Debt Financing", label: "Debt Financing" },
  { value: "Decision Making", label: "Decision Making" },
  { value: "Deep Learning", label: "Deep Learning" },
  { value: "Demand Generation", label: "Demand Generation" },
  { value: "Demand Planning", label: "Demand Planning" },
  { value: "Dentistry", label: "Dentistry" },
  { value: "Derivative Products", label: "Derivative Products" },
  { value: "DevOps", label: "DevOps" },
  { value: "DevOps Toolchain", label: "DevOps Toolchain" },
  { value: "Diesel Engine Repair", label: "Diesel Engine Repair" },
  { value: "Digital Archiving", label: "Digital Archiving" },
  { value: "Digital Forensics", label: "Digital Forensics" },
  {
    value: "Digital Literacy Instruction",
    label: "Digital Literacy Instruction",
  },
  { value: "Digital Marketing", label: "Digital Marketing" },
  { value: "Digital Therapeutics", label: "Digital Therapeutics" },
  { value: "Directing", label: "Directing" },
  { value: "Disaster Recovery", label: "Disaster Recovery" },
  { value: "Discharge Planning", label: "Discharge Planning" },
  { value: "Distance Learning", label: "Distance Learning" },
  { value: "Diversity and Inclusion", label: "Diversity and Inclusion" },
  { value: "Docker", label: "Docker" },
  { value: "Drone Piloting", label: "Drone Piloting" },
  { value: "Drone Surveying", label: "Drone Surveying" },
  { value: "Dynamic Balancing", label: "Dynamic Balancing" },
  { value: "E-commerce Management", label: "E-commerce Management" },
  { value: "E-commerce Strategy", label: "E-commerce Strategy" },
  { value: "E-learning Development", label: "E-learning Development" },
  { value: "EMI/EMC Compliance", label: "EMI/EMC Compliance" },
  { value: "EMR Systems", label: "EMR Systems" },
  {
    value: "ESOP (Employee Stock Ownership Plan)",
    label: "ESOP (Employee Stock Ownership Plan)",
  },
  { value: "ETL (Extract", label: "ETL (Extract" },
  {
    value: "ETL (Extract, Transform, Load)",
    label: "ETL (Extract, Transform, Load)",
  },
  { value: "Early Childhood Education", label: "Early Childhood Education" },
  { value: "Earthworks", label: "Earthworks" },
  { value: "Eco-Friendly Design", label: "Eco-Friendly Design" },
  { value: "Eco-Tourism Development", label: "Eco-Tourism Development" },
  {
    value: "Economic Development Planning",
    label: "Economic Development Planning",
  },
  { value: "Education Administration", label: "Education Administration" },
  { value: "Educational Assessment", label: "Educational Assessment" },
  { value: "Educational Counseling", label: "Educational Counseling" },
  { value: "Educational Technology", label: "Educational Technology" },
  { value: "Electrical Circuit Testing", label: "Electrical Circuit Testing" },
  { value: "Electrical Design", label: "Electrical Design" },
  { value: "Electrical Safety", label: "Electrical Safety" },
  { value: "Electrical Wiring", label: "Electrical Wiring" },
  { value: "Electronic Data Capture", label: "Electronic Data Capture" },
  {
    value: "Electronic Health Records (EHR)",
    label: "Electronic Health Records (EHR)",
  },
  {
    value: "Electronics Troubleshooting",
    label: "Electronics Troubleshooting",
  },
  { value: "Email Marketing", label: "Email Marketing" },
  { value: "Embedded Systems", label: "Embedded Systems" },
  { value: "Emergency Management", label: "Emergency Management" },
  {
    value: "Emergency Medical Technician (EMT)",
    label: "Emergency Medical Technician (EMT)",
  },
  {
    value: "Emergency Response Planning",
    label: "Emergency Response Planning",
  },
  { value: "Emissions Testing", label: "Emissions Testing" },
  { value: "Emotional Intelligence", label: "Emotional Intelligence" },
  { value: "Employee Engagement", label: "Employee Engagement" },
  { value: "Employee Experience", label: "Employee Experience" },
  {
    value: "Employee Lifecycle Management",
    label: "Employee Lifecycle Management",
  },
  {
    value: "Employee Performance Review",
    label: "Employee Performance Review",
  },
  {
    value: "Employee Recognition Programs",
    label: "Employee Recognition Programs",
  },
  { value: "Employee Relations", label: "Employee Relations" },
  {
    value: "Employee Retention Planning",
    label: "Employee Retention Planning",
  },
  {
    value: "Employee Well-being Initiatives",
    label: "Employee Well-being Initiatives",
  },
  { value: "Encryption Key Management", label: "Encryption Key Management" },
  {
    value: "Endpoint Detection and Response (EDR)",
    label: "Endpoint Detection and Response (EDR)",
  },
  { value: "Endpoint Security", label: "Endpoint Security" },
  { value: "Energy Auditing", label: "Energy Auditing" },
  { value: "Energy Management", label: "Energy Management" },
  { value: "Environmental Advocacy", label: "Environmental Advocacy" },
  { value: "Environmental Audits", label: "Environmental Audits" },
  { value: "Environmental Compliance", label: "Environmental Compliance" },
  { value: "Environmental Consulting", label: "Environmental Consulting" },
  {
    value: "Environmental Health and Safety (EHS)",
    label: "Environmental Health and Safety (EHS)",
  },
  {
    value: "Environmental Impact Assessment",
    label: "Environmental Impact Assessment",
  },
  { value: "Environmental Monitoring", label: "Environmental Monitoring" },
  {
    value: "Environmental Risk Assessment",
    label: "Environmental Risk Assessment",
  },
  {
    value: "Environmental Site Assessment",
    label: "Environmental Site Assessment",
  },
  { value: "Equipment Maintenance", label: "Equipment Maintenance" },
  { value: "Ergonomic Assessments", label: "Ergonomic Assessments" },
  { value: "Ergonomics", label: "Ergonomics" },
  { value: "Erosion Control", label: "Erosion Control" },
  { value: "Estate Planning", label: "Estate Planning" },
  { value: "Event Coordination", label: "Event Coordination" },
  { value: "Event Crowd Control", label: "Event Crowd Control" },
  { value: "Event Planning", label: "Event Planning" },
  { value: "Event Promotion", label: "Event Promotion" },
  { value: "Event Security", label: "Event Security" },
  { value: "Event-Driven Architecture", label: "Event-Driven Architecture" },
  { value: "Executive Coaching", label: "Executive Coaching" },
  { value: "Exhibit Curation", label: "Exhibit Curation" },
  { value: "Exhibit Design", label: "Exhibit Design" },
  { value: "Expense Analysis", label: "Expense Analysis" },
  { value: "Experience Rating", label: "Experience Rating" },
  { value: "Experiential Learning", label: "Experiential Learning" },
  { value: "Eye Protection Standards", label: "Eye Protection Standards" },
  { value: "FDA Regulations", label: "FDA Regulations" },
  { value: "Face Recognition", label: "Face Recognition" },
  { value: "Facilities Management", label: "Facilities Management" },
  { value: "Facility Security", label: "Facility Security" },
  { value: "Fiber Optics", label: "Fiber Optics" },
  { value: "Financial Aid Counseling", label: "Financial Aid Counseling" },
  { value: "Financial Analysis", label: "Financial Analysis" },
  { value: "Financial Benchmarking", label: "Financial Benchmarking" },
  { value: "Financial Modeling", label: "Financial Modeling" },
  { value: "Financial Planning", label: "Financial Planning" },
  { value: "Financial Risk Analysis", label: "Financial Risk Analysis" },
  {
    value: "Financial Statement Analysis",
    label: "Financial Statement Analysis",
  },
  {
    value: "Financial Systems Implementation",
    label: "Financial Systems Implementation",
  },
  {
    value: "Finite Element Analysis (FEA)",
    label: "Finite Element Analysis (FEA)",
  },
  { value: "Fire Safety", label: "Fire Safety" },
  { value: "Firewall Administration", label: "Firewall Administration" },
  { value: "Firewall Management", label: "Firewall Management" },
  { value: "First Aid", label: "First Aid" },
  { value: "First Responder Training", label: "First Responder Training" },
  { value: "Fitness App Development", label: "Fitness App Development" },
  { value: "Fixed Asset Management", label: "Fixed Asset Management" },
  { value: "Fixed Assets", label: "Fixed Assets" },
  { value: "Fixed Income Analysis", label: "Fixed Income Analysis" },
  { value: "Fleet Maintenance", label: "Fleet Maintenance" },
  { value: "Fleet Management", label: "Fleet Management" },
  { value: "Fleet Routing", label: "Fleet Routing" },
  { value: "Flight Control Systems", label: "Flight Control Systems" },
  { value: "Flight Operations", label: "Flight Operations" },
  { value: "Flipped Classroom Model", label: "Flipped Classroom Model" },
  { value: "Floodplain Management", label: "Floodplain Management" },
  { value: "Fluid Mechanics", label: "Fluid Mechanics" },
  { value: "Forecasting", label: "Forecasting" },
  { value: "Foreign Exchange (Forex)", label: "Foreign Exchange (Forex)" },
  { value: "Forensic Investigation", label: "Forensic Investigation" },
  { value: "Forensics", label: "Forensics" },
  { value: "Formative Assessment", label: "Formative Assessment" },
  { value: "Foundation Design", label: "Foundation Design" },
  { value: "Fraud Case Management", label: "Fraud Case Management" },
  { value: "Fraud Detection", label: "Fraud Detection" },
  { value: "Fraud Investigation", label: "Fraud Investigation" },
  { value: "Fraud Prevention", label: "Fraud Prevention" },
  { value: "Freight Management", label: "Freight Management" },
  { value: "Freshdesk", label: "Freshdesk" },
  { value: "Frontend Development", label: "Frontend Development" },
  { value: "Full Stack Development", label: "Full Stack Development" },
  { value: "Functional Testing", label: "Functional Testing" },
  { value: "Fundraising Strategy", label: "Fundraising Strategy" },
  {
    value: "GAAP (Generally Accepted Accounting Principles)",
    label: "GAAP (Generally Accepted Accounting Principles)",
  },
  { value: "GDPR Compliance", label: "GDPR Compliance" },
  { value: "GIS Data Visualization", label: "GIS Data Visualization" },
  { value: "Game Design", label: "Game Design" },
  { value: "Game Development", label: "Game Development" },
  { value: "Genetics", label: "Genetics" },
  {
    value: "Geographic Information Systems (GIS)",
    label: "Geographic Information Systems (GIS)",
  },
  { value: "Geolocation Marketing", label: "Geolocation Marketing" },
  { value: "Geological Surveying", label: "Geological Surveying" },
  { value: "Geotechnical Analysis", label: "Geotechnical Analysis" },
  { value: "Gesture Recognition", label: "Gesture Recognition" },
  { value: "Go", label: "Go" },
  { value: "Google Analytics", label: "Google Analytics" },
  { value: "Google Cloud Platform", label: "Google Cloud Platform" },
  { value: "Grant Application Writing", label: "Grant Application Writing" },
  { value: "Grant Writing", label: "Grant Writing" },
  { value: "GraphQL", label: "GraphQL" },
  { value: "Graphic Design", label: "Graphic Design" },
  { value: "Green Infrastructure", label: "Green Infrastructure" },
  { value: "Greenhouse Gas Reporting", label: "Greenhouse Gas Reporting" },
  { value: "Grievance Resolution", label: "Grievance Resolution" },
  { value: "Ground Handling", label: "Ground Handling" },
  { value: "HIPAA Compliance", label: "HIPAA Compliance" },
  {
    value: "HRIS (Human Resources Information System)",
    label: "HRIS (Human Resources Information System)",
  },
  { value: "HTML/CSS", label: "HTML/CSS" },
  { value: "HVAC Design", label: "HVAC Design" },
  { value: "HVAC Installation", label: "HVAC Installation" },
  { value: "Hadoop", label: "Hadoop" },
  { value: "Hazard Analysis", label: "Hazard Analysis" },
  { value: "Hazard Communication", label: "Hazard Communication" },
  { value: "Hazardous Waste Management", label: "Hazardous Waste Management" },
  { value: "Health Data Privacy", label: "Health Data Privacy" },
  { value: "Health Informatics", label: "Health Informatics" },
  {
    value: "Health Information Exchange (HIE)",
    label: "Health Information Exchange (HIE)",
  },
  {
    value: "Health and Safety Regulations",
    label: "Health and Safety Regulations",
  },
  { value: "Healthcare Compliance", label: "Healthcare Compliance" },
  { value: "Healthcare Management", label: "Healthcare Management" },
  { value: "Hedge Fund Management", label: "Hedge Fund Management" },
  { value: "Hedge Funds", label: "Hedge Funds" },
  { value: "High-Speed Design", label: "High-Speed Design" },
  { value: "Historic Preservation", label: "Historic Preservation" },
  { value: "Home Automation", label: "Home Automation" },
  { value: "HubSpot", label: "HubSpot" },
  { value: "Human Capital Strategy", label: "Human Capital Strategy" },
  { value: "Human Resources Management", label: "Human Resources Management" },
  {
    value: "Human-In-The-Loop Machine Learning",
    label: "Human-In-The-Loop Machine Learning",
  },
  { value: "Hybrid Cloud Solutions", label: "Hybrid Cloud Solutions" },
  { value: "Hydropower", label: "Hydropower" },
  { value: "Hyper-V", label: "Hyper-V" },
  {
    value: "IFRS (International Financial Reporting Standards)",
    label: "IFRS (International Financial Reporting Standards)",
  },
  {
    value: "ISO Standards (9001, 14001, etc.)",
    label: "ISO Standards (9001, 14001, etc.)",
  },
  { value: "IT Asset Management", label: "IT Asset Management" },
  { value: "IT Compliance", label: "IT Compliance" },
  {
    value: "ITIL (Information Technology Infrastructure Library)",
    label: "ITIL (Information Technology Infrastructure Library)",
  },
  {
    value: "Identity and Access Management (IAM)",
    label: "Identity and Access Management (IAM)",
  },
  { value: "Illustration", label: "Illustration" },
  { value: "Image Processing", label: "Image Processing" },
  { value: "Image Recognition", label: "Image Recognition" },
  { value: "Import/Export Compliance", label: "Import/Export Compliance" },
  { value: "Incident Analysis", label: "Incident Analysis" },
  {
    value: "Incident Escalation Procedures",
    label: "Incident Escalation Procedures",
  },
  { value: "Incident Response Planning", label: "Incident Response Planning" },
  { value: "Incoterms Knowledge", label: "Incoterms Knowledge" },
  {
    value: "Industrial Control Systems (ICS) Security",
    label: "Industrial Control Systems (ICS) Security",
  },
  { value: "Industrial Hygiene", label: "Industrial Hygiene" },
  { value: "Industrial Safety", label: "Industrial Safety" },
  { value: "Industrial Safety Audits", label: "Industrial Safety Audits" },
  { value: "Influencer Marketing", label: "Influencer Marketing" },
  { value: "Information Governance", label: "Information Governance" },
  { value: "Information Literacy", label: "Information Literacy" },
  {
    value: "Information Security Management",
    label: "Information Security Management",
  },
  {
    value: "Infrastructure as Code (IaC)",
    label: "Infrastructure as Code (IaC)",
  },
  {
    value: "Infrastructure as a Service (IaaS)",
    label: "Infrastructure as a Service (IaaS)",
  },
  { value: "Infusionsoft", label: "Infusionsoft" },
  { value: "Inside Sales", label: "Inside Sales" },
  { value: "Instructional Design", label: "Instructional Design" },
  { value: "Insurance Billing", label: "Insurance Billing" },
  {
    value: "Insurance Fraud Investigation",
    label: "Insurance Fraud Investigation",
  },
  { value: "Insurance Product Design", label: "Insurance Product Design" },
  { value: "Insurance Underwriting", label: "Insurance Underwriting" },
  { value: "Integration Testing", label: "Integration Testing" },
  {
    value: "Intellectual Property Protection",
    label: "Intellectual Property Protection",
  },
  { value: "Intelligence Analysis", label: "Intelligence Analysis" },
  {
    value: "Internal Control Evaluation",
    label: "Internal Control Evaluation",
  },
  { value: "Internet of Things (IoT)", label: "Internet of Things (IoT)" },
  { value: "Interpersonal Skills", label: "Interpersonal Skills" },
  { value: "Intrusion Detection", label: "Intrusion Detection" },
  { value: "Intrusion Prevention", label: "Intrusion Prevention" },
  { value: "Inventory Accuracy", label: "Inventory Accuracy" },
  { value: "Inventory Control", label: "Inventory Control" },
  { value: "Inventory Forecasting", label: "Inventory Forecasting" },
  { value: "Inventory Management", label: "Inventory Management" },
  { value: "Inventory Reconciliation", label: "Inventory Reconciliation" },
  { value: "Inventory Valuation", label: "Inventory Valuation" },
  { value: "Investigation", label: "Investigation" },
  { value: "Investment Analysis", label: "Investment Analysis" },
  { value: "Investment Banking", label: "Investment Banking" },
  { value: "Invoicing and Billing", label: "Invoicing and Billing" },
  { value: "JIRA", label: "JIRA" },
  { value: "Janitorial Management", label: "Janitorial Management" },
  { value: "Java", label: "Java" },
  { value: "JavaScript", label: "JavaScript" },
  { value: "Job Evaluation", label: "Job Evaluation" },
  { value: "Job Safety Analysis", label: "Job Safety Analysis" },
  { value: "KYC (Know Your Customer)", label: "KYC (Know Your Customer)" },
  { value: "Kaizen", label: "Kaizen" },
  { value: "Kanban", label: "Kanban" },
  { value: "Key Account Management", label: "Key Account Management" },
  { value: "Kubernetes", label: "Kubernetes" },
  {
    value: "LEED Certification Knowledge",
    label: "LEED Certification Knowledge",
  },
  { value: "Labor Dispute Resolution", label: "Labor Dispute Resolution" },
  { value: "Labor Law", label: "Labor Law" },
  { value: "Labor Relations", label: "Labor Relations" },
  { value: "Laboratory Skills", label: "Laboratory Skills" },
  { value: "Land Surveying", label: "Land Surveying" },
  { value: "Land Use Planning", label: "Land Use Planning" },
  { value: "Landing Page Optimization", label: "Landing Page Optimization" },
  { value: "Landscape Design", label: "Landscape Design" },
  { value: "Language Acquisition", label: "Language Acquisition" },
  { value: "Laser Cutting", label: "Laser Cutting" },
  { value: "Laser Technology", label: "Laser Technology" },
  { value: "Layout Design", label: "Layout Design" },
  { value: "Lead Generation", label: "Lead Generation" },
  { value: "Lead Nurturing", label: "Lead Nurturing" },
  { value: "Lead Scoring", label: "Lead Scoring" },
  { value: "Leadership", label: "Leadership" },
  { value: "Lean Manufacturing", label: "Lean Manufacturing" },
  { value: "Lean Six Sigma", label: "Lean Six Sigma" },
  { value: "Learning Analytics", label: "Learning Analytics" },
  { value: "Learning Content Creation", label: "Learning Content Creation" },
  { value: "Learning Disabilities", label: "Learning Disabilities" },
  {
    value: "Learning Management Systems (LMS)",
    label: "Learning Management Systems (LMS)",
  },
  {
    value: "Learning Outcomes Measurement",
    label: "Learning Outcomes Measurement",
  },
  { value: "Legal Compliance", label: "Legal Compliance" },
  { value: "Lesson Planning", label: "Lesson Planning" },
  { value: "LiDAR Processing", label: "LiDAR Processing" },
  { value: "Library Administration", label: "Library Administration" },
  { value: "Library Cataloging", label: "Library Cataloging" },
  { value: "Library Science", label: "Library Science" },
  { value: "Lidar", label: "Lidar" },
  { value: "Life Cycle Analysis", label: "Life Cycle Analysis" },
  { value: "Life Insurance", label: "Life Insurance" },
  { value: "Lighting Design", label: "Lighting Design" },
  { value: "Linux", label: "Linux" },
  { value: "Literature Review", label: "Literature Review" },
  { value: "Litigation Management", label: "Litigation Management" },
  { value: "Load Testing", label: "Load Testing" },
  { value: "Loan Processing", label: "Loan Processing" },
  { value: "Lobbying", label: "Lobbying" },
  { value: "Lockout/Tagout Procedures", label: "Lockout/Tagout Procedures" },
  { value: "Logistics", label: "Logistics" },
  { value: "Logistics Planning", label: "Logistics Planning" },
  { value: "Loss Prevention", label: "Loss Prevention" },
  { value: "Loss Ratios", label: "Loss Ratios" },
  { value: "MATLAB", label: "MATLAB" },
  { value: "Machine Guarding", label: "Machine Guarding" },
  { value: "Machine Learning", label: "Machine Learning" },
  {
    value: "Machine Learning Model Deployment",
    label: "Machine Learning Model Deployment",
  },
  {
    value: "Machine Learning Operations (MLOps)",
    label: "Machine Learning Operations (MLOps)",
  },
  { value: "Machine Maintenance", label: "Machine Maintenance" },
  { value: "Malware Analysis", label: "Malware Analysis" },
  {
    value: "Managed Detection and Response (MDR)",
    label: "Managed Detection and Response (MDR)",
  },
  { value: "Management Buyouts (MBO)", label: "Management Buyouts (MBO)" },
  { value: "Manual Testing", label: "Manual Testing" },
  { value: "Manufacturing Management", label: "Manufacturing Management" },
  { value: "Marine Insurance", label: "Marine Insurance" },
  { value: "Market Analysis", label: "Market Analysis" },
  { value: "Market Entry Strategy", label: "Market Entry Strategy" },
  { value: "Market Research", label: "Market Research" },
  { value: "Market Segmentation", label: "Market Segmentation" },
  { value: "Marketo", label: "Marketo" },
  {
    value: "Marriage and Family Therapy",
    label: "Marriage and Family Therapy",
  },
  { value: "Masonry", label: "Masonry" },
  { value: "Master Data Management", label: "Master Data Management" },
  {
    value: "Material Handling Equipment",
    label: "Material Handling Equipment",
  },
  { value: "Material Handling Safety", label: "Material Handling Safety" },
  {
    value: "Material Safety Data Sheets (MSDS)",
    label: "Material Safety Data Sheets (MSDS)",
  },
  { value: "Material Science", label: "Material Science" },
  { value: "Material Testing", label: "Material Testing" },
  { value: "Materials Handling", label: "Materials Handling" },
  { value: "Mechanical Design", label: "Mechanical Design" },
  { value: "Mechanical Drafting", label: "Mechanical Drafting" },
  { value: "Mechanical Testing", label: "Mechanical Testing" },
  { value: "Media Relations", label: "Media Relations" },
  { value: "Medical Claims Processing", label: "Medical Claims Processing" },
  { value: "Medical Coding", label: "Medical Coding" },
  { value: "Medical Credentialing", label: "Medical Credentialing" },
  { value: "Medical Device Management", label: "Medical Device Management" },
  { value: "Medical Device Security", label: "Medical Device Security" },
  { value: "Medical Transcription", label: "Medical Transcription" },
  { value: "Mental Health Therapy", label: "Mental Health Therapy" },
  {
    value: "Mergers & Acquisitions (M&A)",
    label: "Mergers & Acquisitions (M&A)",
  },
  { value: "Microservices Architecture", label: "Microservices Architecture" },
  { value: "Microsoft Office", label: "Microsoft Office" },
  { value: "Microsoft Teams", label: "Microsoft Teams" },
  { value: "Microwave Engineering", label: "Microwave Engineering" },
  {
    value: "Mixed-Use Development Planning",
    label: "Mixed-Use Development Planning",
  },
  {
    value: "Mobile Application Security",
    label: "Mobile Application Security",
  },
  {
    value: "Mobile Device Management (MDM)",
    label: "Mobile Device Management (MDM)",
  },
  { value: "Mobile Marketing", label: "Mobile Marketing" },
  { value: "Mobile UI Design", label: "Mobile UI Design" },
  { value: "Monte Carlo Simulation", label: "Monte Carlo Simulation" },
  { value: "Montessori Method", label: "Montessori Method" },
  { value: "Mortgage Lending", label: "Mortgage Lending" },
  { value: "Motivational Interviewing", label: "Motivational Interviewing" },
  { value: "Motor Controls", label: "Motor Controls" },
  { value: "Multi-Cloud Strategy", label: "Multi-Cloud Strategy" },
  { value: "Museum Curation", label: "Museum Curation" },
  { value: "Museum Security", label: "Museum Security" },
  { value: "Music Production", label: "Music Production" },
  { value: "Music Therapy", label: "Music Therapy" },
  { value: "Mutual Funds", label: "Mutual Funds" },
  {
    value: "Natural Language Generation",
    label: "Natural Language Generation",
  },
  {
    value: "Natural Language Generation (NLG)",
    label: "Natural Language Generation (NLG)",
  },
  {
    value: "Natural Language Processing",
    label: "Natural Language Processing",
  },
  {
    value: "Natural Resource Conservation",
    label: "Natural Resource Conservation",
  },
  { value: "Natural Resource Policy", label: "Natural Resource Policy" },
  { value: "Navigation Algorithms", label: "Navigation Algorithms" },
  { value: "Navigation Systems", label: "Navigation Systems" },
  { value: "Negotiation", label: "Negotiation" },
  {
    value: "Network Access Control (NAC)",
    label: "Network Access Control (NAC)",
  },
  { value: "Network Design", label: "Network Design" },
  { value: "Network Security", label: "Network Security" },
  {
    value: "Network Security Management",
    label: "Network Security Management",
  },
  { value: "Network Troubleshooting", label: "Network Troubleshooting" },
  { value: "Networking", label: "Networking" },
  { value: "Neural Networks", label: "Neural Networks" },
  {
    value: "Neurodevelopmental Disorders",
    label: "Neurodevelopmental Disorders",
  },
  { value: "Node.js", label: "Node.js" },
  { value: "Noise Exposure Assessment", label: "Noise Exposure Assessment" },
  { value: "Noise Reduction", label: "Noise Reduction" },
  {
    value: "Nonprofit Board Development",
    label: "Nonprofit Board Development",
  },
  {
    value: "Nonprofit Financial Management",
    label: "Nonprofit Financial Management",
  },
  { value: "Nonprofit Management", label: "Nonprofit Management" },
  { value: "Nursing", label: "Nursing" },
  { value: "OSHA Compliance", label: "OSHA Compliance" },
  {
    value: "Occupational Safety Training",
    label: "Occupational Safety Training",
  },
  { value: "Occupational Therapy", label: "Occupational Therapy" },
  { value: "Onboarding", label: "Onboarding" },
  { value: "OpenStack", label: "OpenStack" },
  { value: "Operational Analysis", label: "Operational Analysis" },
  { value: "Operational Audits", label: "Operational Audits" },
  { value: "Optical Systems Design", label: "Optical Systems Design" },
  { value: "Oracle", label: "Oracle" },
  { value: "Order Fulfillment", label: "Order Fulfillment" },
  { value: "Order Processing", label: "Order Processing" },
  { value: "Organizational Behavior", label: "Organizational Behavior" },
  { value: "Organizational Development", label: "Organizational Development" },
  { value: "PCB Design", label: "PCB Design" },
  { value: "PCI-DSS Compliance", label: "PCI-DSS Compliance" },
  { value: "PLC Programming", label: "PLC Programming" },
  { value: "PLC Troubleshooting", label: "PLC Troubleshooting" },
  { value: "Packaging Design", label: "Packaging Design" },
  { value: "Packing and Crating", label: "Packing and Crating" },
  { value: "Parcel Tracking", label: "Parcel Tracking" },
  { value: "Pardot", label: "Pardot" },
  {
    value: "Parent-Teacher Communication",
    label: "Parent-Teacher Communication",
  },
  { value: "Partner Management", label: "Partner Management" },
  { value: "Patch Management", label: "Patch Management" },
  { value: "Pathfinding", label: "Pathfinding" },
  { value: "Patient Advocacy", label: "Patient Advocacy" },
  { value: "Patient Care", label: "Patient Care" },
  { value: "Patient Scheduling", label: "Patient Scheduling" },
  { value: "Payment Fraud Detection", label: "Payment Fraud Detection" },
  { value: "Payroll", label: "Payroll" },
  { value: "Payroll Processing", label: "Payroll Processing" },
  { value: "Penetration Testing", label: "Penetration Testing" },
  { value: "PeopleSoft", label: "PeopleSoft" },
  { value: "Performance Testing", label: "Performance Testing" },
  { value: "Perimeter Security", label: "Perimeter Security" },
  { value: "Pharmaceutical Development", label: "Pharmaceutical Development" },
  { value: "Photography", label: "Photography" },
  { value: "Physical Therapy", label: "Physical Therapy" },
  { value: "Pick and Pack Operations", label: "Pick and Pack Operations" },
  { value: "Pilot Training", label: "Pilot Training" },
  { value: "Pipeline Management", label: "Pipeline Management" },
  { value: "Piping Design", label: "Piping Design" },
  { value: "Piping Systems", label: "Piping Systems" },
  {
    value: "Platform as a Service (PaaS)",
    label: "Platform as a Service (PaaS)",
  },
  { value: "Plumbing", label: "Plumbing" },
  { value: "Policy Administration", label: "Policy Administration" },
  { value: "Policy Cancellation", label: "Policy Cancellation" },
  { value: "Policy Development", label: "Policy Development" },
  { value: "Policy Renewals", label: "Policy Renewals" },
  { value: "Portfolio Diversification", label: "Portfolio Diversification" },
  { value: "Portfolio Management", label: "Portfolio Management" },
  { value: "Post-Sales Support", label: "Post-Sales Support" },
  { value: "Power BI", label: "Power BI" },
  { value: "Power Distribution", label: "Power Distribution" },
  { value: "Pre-Sales Support", label: "Pre-Sales Support" },
  { value: "Predictive Analytics", label: "Predictive Analytics" },
  { value: "Predictive Maintenance", label: "Predictive Maintenance" },
  { value: "Predictive Modeling", label: "Predictive Modeling" },
  { value: "Press Release Writing", label: "Press Release Writing" },
  { value: "Price Sensitivity Analysis", label: "Price Sensitivity Analysis" },
  { value: "Private Equity", label: "Private Equity" },
  { value: "Private Investigations", label: "Private Investigations" },
  { value: "Problem-Solving", label: "Problem-Solving" },
  {
    value: "Process Capability Analysis",
    label: "Process Capability Analysis",
  },
  { value: "Process Documentation", label: "Process Documentation" },
  { value: "Process Improvement", label: "Process Improvement" },
  { value: "Process Mapping", label: "Process Mapping" },
  { value: "Procurement Strategy", label: "Procurement Strategy" },
  { value: "Product Demonstrations", label: "Product Demonstrations" },
  { value: "Product Demos", label: "Product Demos" },
  { value: "Product Innovation", label: "Product Innovation" },
  { value: "Product Launch Planning", label: "Product Launch Planning" },
  { value: "Product Liability", label: "Product Liability" },
  { value: "Product Management", label: "Product Management" },
  { value: "Product Roadmap Planning", label: "Product Roadmap Planning" },
  { value: "Product Testing", label: "Product Testing" },
  { value: "Production Optimization", label: "Production Optimization" },
  { value: "Production Planning", label: "Production Planning" },
  { value: "Production Scheduling", label: "Production Scheduling" },
  { value: "Profit and Loss Analysis", label: "Profit and Loss Analysis" },
  { value: "Profitability Analysis", label: "Profitability Analysis" },
  { value: "Programming", label: "Programming" },
  { value: "Progress Monitoring", label: "Progress Monitoring" },
  { value: "Project Estimation", label: "Project Estimation" },
  { value: "Project Management", label: "Project Management" },
  { value: "Project Scheduling", label: "Project Scheduling" },
  { value: "Proofreading", label: "Proofreading" },
  { value: "Property Appraisal", label: "Property Appraisal" },
  { value: "Property Insurance", label: "Property Insurance" },
  { value: "Proposal Writing", label: "Proposal Writing" },
  { value: "Prototyping", label: "Prototyping" },
  { value: "Psychoeducation", label: "Psychoeducation" },
  { value: "Psychology", label: "Psychology" },
  { value: "Public Affairs", label: "Public Affairs" },
  { value: "Public Cloud Solutions", label: "Public Cloud Solutions" },
  {
    value: "Public Key Infrastructure (PKI)",
    label: "Public Key Infrastructure (PKI)",
  },
  { value: "Public Policy Analysis", label: "Public Policy Analysis" },
  { value: "Public Safety Liaison", label: "Public Safety Liaison" },
  { value: "Public Speaking", label: "Public Speaking" },
  {
    value: "Public Speaking Engagements",
    label: "Public Speaking Engagements",
  },
  { value: "Puppet", label: "Puppet" },
  { value: "PyTorch", label: "PyTorch" },
  { value: "Python", label: "Python" },
  { value: "Qualitative Research", label: "Qualitative Research" },
  { value: "Quality Assurance", label: "Quality Assurance" },
  { value: "Quality Control", label: "Quality Control" },
  {
    value: "Quality of Life (QoL) Analysis",
    label: "Quality of Life (QoL) Analysis",
  },
  { value: "Quantitative Research", label: "Quantitative Research" },
  { value: "Quota Management", label: "Quota Management" },
  { value: "R", label: "R" },
  { value: "RESTful Services", label: "RESTful Services" },
  { value: "RF Engineering", label: "RF Engineering" },
  { value: "Radar", label: "Radar" },
  { value: "Radiation Safety", label: "Radiation Safety" },
  { value: "Radiology", label: "Radiology" },
  { value: "Railway Operations", label: "Railway Operations" },
  { value: "Rapid Prototyping", label: "Rapid Prototyping" },
  { value: "React", label: "React" },
  { value: "Real Estate Investment", label: "Real Estate Investment" },
  { value: "Real Estate Management", label: "Real Estate Management" },
  {
    value: "Real Estate Portfolio Management",
    label: "Real Estate Portfolio Management",
  },
  { value: "Real-Time Analytics", label: "Real-Time Analytics" },
  { value: "Real-Time Data Processing", label: "Real-Time Data Processing" },
  { value: "Real-Time Monitoring", label: "Real-Time Monitoring" },
  { value: "Recommendation Systems", label: "Recommendation Systems" },
  { value: "Records Management", label: "Records Management" },
  { value: "Recruitment", label: "Recruitment" },
  { value: "Recycling Operations", label: "Recycling Operations" },
  { value: "Red Teaming", label: "Red Teaming" },
  { value: "Regression Testing", label: "Regression Testing" },
  { value: "Regulatory Reporting", label: "Regulatory Reporting" },
  { value: "Rehabilitation Planning", label: "Rehabilitation Planning" },
  { value: "Reinsurance", label: "Reinsurance" },
  { value: "Reinsurance Placement", label: "Reinsurance Placement" },
  { value: "Remote Piloting", label: "Remote Piloting" },
  { value: "Remote Sensing", label: "Remote Sensing" },
  { value: "Remote Sensing Analysis", label: "Remote Sensing Analysis" },
  { value: "Renewable Energy Planning", label: "Renewable Energy Planning" },
  {
    value: "Renewable Resource Management",
    label: "Renewable Resource Management",
  },
  { value: "Renewable Resource Policy", label: "Renewable Resource Policy" },
  { value: "Report Writing", label: "Report Writing" },
  { value: "Research", label: "Research" },
  { value: "Research Databases", label: "Research Databases" },
  { value: "Reseller Management", label: "Reseller Management" },
  { value: "Respiratory Protection", label: "Respiratory Protection" },
  { value: "Retargeting", label: "Retargeting" },
  { value: "Retention Strategies", label: "Retention Strategies" },
  { value: "Retirement Planning", label: "Retirement Planning" },
  { value: "Returns Processing", label: "Returns Processing" },
  { value: "Revenue Cycle Management", label: "Revenue Cycle Management" },
  { value: "Revenue Forecasting", label: "Revenue Forecasting" },
  { value: "Revenue Management", label: "Revenue Management" },
  { value: "Revenue Recognition", label: "Revenue Recognition" },
  { value: "Reverse Logistics", label: "Reverse Logistics" },
  { value: "Risk Adjustment", label: "Risk Adjustment" },
  { value: "Risk Assessment", label: "Risk Assessment" },
  { value: "Risk Assessment Matrix", label: "Risk Assessment Matrix" },
  { value: "Risk Management", label: "Risk Management" },
  { value: "Risk Mitigation", label: "Risk Mitigation" },
  { value: "Risk Mitigation Strategy", label: "Risk Mitigation Strategy" },
  { value: "Risk Scoring", label: "Risk Scoring" },
  { value: "Robotic Arm Programming", label: "Robotic Arm Programming" },
  { value: "Robotics", label: "Robotics" },
  { value: "Roofing", label: "Roofing" },
  { value: "Root Cause Analysis", label: "Root Cause Analysis" },
  { value: "Route Optimization", label: "Route Optimization" },
  { value: "Ruby on Rails", label: "Ruby on Rails" },
  { value: "SAP", label: "SAP" },
  { value: "SAS", label: "SAS" },
  { value: "SAT/ACT Prep", label: "SAT/ACT Prep" },
  { value: "SD-WAN", label: "SD-WAN" },
  { value: "SEO", label: "SEO" },
  {
    value: "SIEM (Security Information and Event Management)",
    label: "SIEM (Security Information and Event Management)",
  },
  {
    value: "SOC (Security Operations Center)",
    label: "SOC (Security Operations Center)",
  },
  { value: "SPSS", label: "SPSS" },
  { value: "SQL", label: "SQL" },
  { value: "STEM Education", label: "STEM Education" },
  { value: "SWOT Analysis", label: "SWOT Analysis" },
  { value: "Safety Audits", label: "Safety Audits" },
  {
    value: "Safety Protocol Development",
    label: "Safety Protocol Development",
  },
  { value: "Safety Training", label: "Safety Training" },
  { value: "Sales", label: "Sales" },
  { value: "Sales Enablement", label: "Sales Enablement" },
  { value: "Sales Forecasting", label: "Sales Forecasting" },
  { value: "Sales Funnel Optimization", label: "Sales Funnel Optimization" },
  { value: "Sales Operations", label: "Sales Operations" },
  { value: "Sales Pipeline Management", label: "Sales Pipeline Management" },
  { value: "Sales Presentations", label: "Sales Presentations" },
  { value: "Sales Training", label: "Sales Training" },
  { value: "Salesforce", label: "Salesforce" },
  { value: "Sarbanes-Oxley Compliance", label: "Sarbanes-Oxley Compliance" },
  { value: "Satellite Image Analysis", label: "Satellite Image Analysis" },
  { value: "Satellite Imaging", label: "Satellite Imaging" },
  { value: "Scaffolding", label: "Scaffolding" },
  { value: "Scientific Research", label: "Scientific Research" },
  { value: "Scripting", label: "Scripting" },
  { value: "Scriptwriting", label: "Scriptwriting" },
  { value: "Scrum", label: "Scrum" },
  {
    value: "Search Engine Marketing (SEM)",
    label: "Search Engine Marketing (SEM)",
  },
  {
    value: "Search and Rescue Operations",
    label: "Search and Rescue Operations",
  },
  { value: "Secure Coding Practices", label: "Secure Coding Practices" },
  {
    value: "Security Awareness Programs",
    label: "Security Awareness Programs",
  },
  {
    value: "Security Awareness Training",
    label: "Security Awareness Training",
  },
  { value: "Security Incident Response", label: "Security Incident Response" },
  {
    value: "Security Policy Development",
    label: "Security Policy Development",
  },
  { value: "Sensor Fusion", label: "Sensor Fusion" },
  { value: "Sensors and Actuators", label: "Sensors and Actuators" },
  { value: "Sentiment Analysis", label: "Sentiment Analysis" },
  { value: "Server Management", label: "Server Management" },
  { value: "Serverless Computing", label: "Serverless Computing" },
  {
    value: "Service-Level Agreements (SLA)",
    label: "Service-Level Agreements (SLA)",
  },
  { value: "Set Design", label: "Set Design" },
  { value: "SharePoint", label: "SharePoint" },
  { value: "Shipping Coordination", label: "Shipping Coordination" },
  { value: "Six Sigma", label: "Six Sigma" },
  { value: "Slack", label: "Slack" },
  { value: "Smart Home Technology", label: "Smart Home Technology" },
  { value: "Snowflake", label: "Snowflake" },
  { value: "Social Engineering", label: "Social Engineering" },
  { value: "Social Media Advertising", label: "Social Media Advertising" },
  { value: "Social Media Management", label: "Social Media Management" },
  { value: "Social Work", label: "Social Work" },
  {
    value: "Social and Emotional Learning",
    label: "Social and Emotional Learning",
  },
  { value: "Soft Skills Training", label: "Soft Skills Training" },
  {
    value: "Software Development Lifecycle (SDLC)",
    label: "Software Development Lifecycle (SDLC)",
  },
  { value: "Software Testing", label: "Software Testing" },
  {
    value: "Software Vulnerability Management",
    label: "Software Vulnerability Management",
  },
  { value: "Soil Conservation", label: "Soil Conservation" },
  { value: "Soil Testing", label: "Soil Testing" },
  { value: "Solar Energy", label: "Solar Energy" },
  { value: "SolidWorks", label: "SolidWorks" },
  { value: "Sound Design", label: "Sound Design" },
  { value: "Sound Engineering", label: "Sound Engineering" },
  { value: "Sound Mixing", label: "Sound Mixing" },
  { value: "Space Planning", label: "Space Planning" },
  { value: "Spark", label: "Spark" },
  { value: "Spatial Analysis", label: "Spatial Analysis" },
  { value: "Special Education", label: "Special Education" },
  { value: "Specialized Instruction", label: "Specialized Instruction" },
  { value: "Speech Therapy", label: "Speech Therapy" },
  { value: "Speech Writing", label: "Speech Writing" },
  { value: "Spill Containment", label: "Spill Containment" },
  { value: "Spill Response", label: "Spill Response" },
  { value: "Stakeholder Analysis", label: "Stakeholder Analysis" },
  { value: "Stakeholder Engagement", label: "Stakeholder Engagement" },
  { value: "Statistical Analysis", label: "Statistical Analysis" },
  { value: "Statistical Computing", label: "Statistical Computing" },
  { value: "Statistical Modeling", label: "Statistical Modeling" },
  {
    value: "Statistical Process Control (SPC)",
    label: "Statistical Process Control (SPC)",
  },
  { value: "Statutory Reporting", label: "Statutory Reporting" },
  {
    value: "Stock Option Plan Management",
    label: "Stock Option Plan Management",
  },
  { value: "Storytelling", label: "Storytelling" },
  { value: "Strategic HR Planning", label: "Strategic HR Planning" },
  { value: "Strategic Planning", label: "Strategic Planning" },
  { value: "Strength of Materials", label: "Strength of Materials" },
  { value: "Structural Analysis", label: "Structural Analysis" },
  { value: "Structural Dynamics", label: "Structural Dynamics" },
  {
    value: "Structural Equation Modeling",
    label: "Structural Equation Modeling",
  },
  { value: "Structured Finance", label: "Structured Finance" },
  { value: "Student Data Analysis", label: "Student Data Analysis" },
  {
    value: "Student Engagement Strategies",
    label: "Student Engagement Strategies",
  },
  { value: "Subrogation", label: "Subrogation" },
  { value: "Substance Abuse Counseling", label: "Substance Abuse Counseling" },
  { value: "Succession Management", label: "Succession Management" },
  { value: "Succession Planning", label: "Succession Planning" },
  { value: "Supplier Audits", label: "Supplier Audits" },
  {
    value: "Supplier Relationship Management",
    label: "Supplier Relationship Management",
  },
  { value: "Supply Chain Analytics", label: "Supply Chain Analytics" },
  { value: "Supply Chain Forecasting", label: "Supply Chain Forecasting" },
  { value: "Supply Chain Management", label: "Supply Chain Management" },
  { value: "Supply Chain Optimization", label: "Supply Chain Optimization" },
  {
    value: "Supply Chain Risk Management",
    label: "Supply Chain Risk Management",
  },
  { value: "Surface Finishing", label: "Surface Finishing" },
  { value: "Surveillance", label: "Surveillance" },
  { value: "Surveillance Monitoring", label: "Surveillance Monitoring" },
  { value: "Surveying", label: "Surveying" },
  { value: "Sustainability Planning", label: "Sustainability Planning" },
  { value: "Sustainable Sourcing", label: "Sustainable Sourcing" },
  { value: "Swift", label: "Swift" },
  { value: "Systems Administration", label: "Systems Administration" },
  { value: "Tableau", label: "Tableau" },
  { value: "Takt Time Analysis", label: "Takt Time Analysis" },
  { value: "Talent Assessment", label: "Talent Assessment" },
  { value: "Talent Development", label: "Talent Development" },
  { value: "Tax Compliance", label: "Tax Compliance" },
  { value: "Tax Planning", label: "Tax Planning" },
  { value: "Tax Strategy", label: "Tax Strategy" },
  { value: "Teamwork", label: "Teamwork" },
  { value: "Technical Support", label: "Technical Support" },
  { value: "Technical Writing", label: "Technical Writing" },
  { value: "Telecom Management", label: "Telecom Management" },
  { value: "Telehealth Solutions", label: "Telehealth Solutions" },
  { value: "Telemedicine", label: "Telemedicine" },
  { value: "Telemetry Analysis", label: "Telemetry Analysis" },
  { value: "Tenant Relations", label: "Tenant Relations" },
  { value: "TensorFlow", label: "TensorFlow" },
  { value: "Teradata", label: "Teradata" },
  { value: "Terraform", label: "Terraform" },
  { value: "Test Automation", label: "Test Automation" },
  { value: "Test Preparation", label: "Test Preparation" },
  { value: "Text Mining", label: "Text Mining" },
  { value: "Thermal Management", label: "Thermal Management" },
  { value: "Thermodynamics", label: "Thermodynamics" },
  {
    value: "Third-Party Claims Administration",
    label: "Third-Party Claims Administration",
  },
  {
    value: "Third-Party Risk Management",
    label: "Third-Party Risk Management",
  },
  { value: "Threat Hunting", label: "Threat Hunting" },
  {
    value: "Threat Intelligence Analysis",
    label: "Threat Intelligence Analysis",
  },
  {
    value: "Threat Intelligence Platforms",
    label: "Threat Intelligence Platforms",
  },
  { value: "Threat Modeling", label: "Threat Modeling" },
  { value: "Time Management", label: "Time Management" },
  { value: "Tokenization", label: "Tokenization" },
  { value: "Total Rewards Planning", label: "Total Rewards Planning" },
  { value: "Trade Show Management", label: "Trade Show Management" },
  { value: "Trade Union Relations", label: "Trade Union Relations" },
  { value: "Training Needs Analysis", label: "Training Needs Analysis" },
  { value: "Training and Development", label: "Training and Development" },
  {
    value: "Transit-Oriented Development",
    label: "Transit-Oriented Development",
  },
  { value: "Translation", label: "Translation" },
  {
    value: "Transportation Cost Management",
    label: "Transportation Cost Management",
  },
  { value: "Transportation Management", label: "Transportation Management" },
  { value: "Transportation Planning", label: "Transportation Planning" },
  { value: "Treasury Management", label: "Treasury Management" },
  { value: "Trello", label: "Trello" },
  { value: "Trend Analysis", label: "Trend Analysis" },
  { value: "Troubleshooting", label: "Troubleshooting" },
  { value: "Tutoring", label: "Tutoring" },
  { value: "Typography", label: "Typography" },
  { value: "UI Design", label: "UI Design" },
  { value: "UX Design", label: "UX Design" },
  {
    value: "Underwriting Risk Assessment",
    label: "Underwriting Risk Assessment",
  },
  { value: "Union Negotiations", label: "Union Negotiations" },
  { value: "Unit Cost Analysis", label: "Unit Cost Analysis" },
  { value: "Unit Testing", label: "Unit Testing" },
  { value: "Unmanned Aerial Systems", label: "Unmanned Aerial Systems" },
  { value: "Up-Selling", label: "Up-Selling" },
  { value: "Urban Landscape Planning", label: "Urban Landscape Planning" },
  { value: "Urban Planning", label: "Urban Planning" },
  { value: "Usability Testing", label: "Usability Testing" },
  { value: "User Behavior Analytics", label: "User Behavior Analytics" },
  {
    value: "User Experience (UX) Writing",
    label: "User Experience (UX) Writing",
  },
  { value: "User Experience Research", label: "User Experience Research" },
  { value: "User Persona Development", label: "User Persona Development" },
  { value: "User Research", label: "User Research" },
  { value: "User Story Creation", label: "User Story Creation" },
  {
    value: "User and Entity Behavior Analytics (UEBA)",
    label: "User and Entity Behavior Analytics (UEBA)",
  },
  { value: "Utilization Review", label: "Utilization Review" },
  { value: "VIP Protection", label: "VIP Protection" },
  { value: "VMware", label: "VMware" },
  { value: "VPN Configuration", label: "VPN Configuration" },
  { value: "Valuation Models", label: "Valuation Models" },
  { value: "Value Stream Mapping", label: "Value Stream Mapping" },
  { value: "Vendor Compliance", label: "Vendor Compliance" },
  { value: "Venture Capital", label: "Venture Capital" },
  { value: "Version Control (Git)", label: "Version Control (Git)" },
  { value: "Veterinary Care", label: "Veterinary Care" },
  { value: "Vibration Analysis", label: "Vibration Analysis" },
  { value: "Video Editing", label: "Video Editing" },
  { value: "Video Production", label: "Video Production" },
  {
    value: "Virtual Classroom Management",
    label: "Virtual Classroom Management",
  },
  { value: "Virtual Reality", label: "Virtual Reality" },
  { value: "Virtualization", label: "Virtualization" },
  { value: "Visual Storytelling", label: "Visual Storytelling" },
  { value: "Voice Acting", label: "Voice Acting" },
  { value: "Voice Control Systems", label: "Voice Control Systems" },
  { value: "Voice Recognition", label: "Voice Recognition" },
  { value: "Volunteer Coordination", label: "Volunteer Coordination" },
  { value: "Vulnerability Management", label: "Vulnerability Management" },
  { value: "Vulnerability Scanning", label: "Vulnerability Scanning" },
  {
    value: "Warehouse Layout Optimization",
    label: "Warehouse Layout Optimization",
  },
  { value: "Warehouse Management", label: "Warehouse Management" },
  { value: "Waste Management", label: "Waste Management" },
  { value: "Waste Reduction", label: "Waste Reduction" },
  { value: "Waste Reduction Strategies", label: "Waste Reduction Strategies" },
  { value: "Waste-to-Energy Conversion", label: "Waste-to-Energy Conversion" },
  { value: "Water Resource Management", label: "Water Resource Management" },
  { value: "Watershed Management", label: "Watershed Management" },
  { value: "Wealth Management", label: "Wealth Management" },
  { value: "Wearable Technology", label: "Wearable Technology" },
  {
    value: "Web Application Firewalls (WAF)",
    label: "Web Application Firewalls (WAF)",
  },
  { value: "Web UI Design", label: "Web UI Design" },
  { value: "Weld Quality Analysis", label: "Weld Quality Analysis" },
  { value: "Welding", label: "Welding" },
  { value: "Welding Inspection", label: "Welding Inspection" },
  { value: "Wetland Delineation", label: "Wetland Delineation" },
  {
    value: "Wildlife Habitat Restoration",
    label: "Wildlife Habitat Restoration",
  },
  { value: "Wind Energy", label: "Wind Energy" },
  { value: "Windows", label: "Windows" },
  { value: "Wire Transfer Processing", label: "Wire Transfer Processing" },
  { value: "Wireframing", label: "Wireframing" },
  { value: "Workflow Automation", label: "Workflow Automation" },
  { value: "Workforce Analytics", label: "Workforce Analytics" },
  { value: "Workforce Development", label: "Workforce Development" },
  { value: "Workforce Scheduling", label: "Workforce Scheduling" },
  { value: "Workplace Safety", label: "Workplace Safety" },
  {
    value: "Workplace Violence Prevention",
    label: "Workplace Violence Prevention",
  },
  { value: "Writing", label: "Writing" },
  { value: "Youth Development", label: "Youth Development" },
  { value: "Zendesk", label: "Zendesk" },
  { value: "Zero Trust Security", label: "Zero Trust Security" },
  {
    value: "Zoning and Land Use Regulations",
    label: "Zoning and Land Use Regulations",
  },
  { value: "iOS Development", label: "iOS Development" },
];
