import * as Yup from "yup";

export const schemas = {
  entering: Yup.object().shape({
    desiredPosition: Yup.string().trim(),
    phone: Yup.string().trim(),
    email: Yup.string().trim(),
    LinkedIn: Yup.string().trim(),
    professionalSummary: Yup.string().trim().max(500, "Too long"),
    projectName: Yup.string().trim(),
    role: Yup.string().trim().max(500, "Too long"),
    projectLink: Yup.string().trim(),
    companyName: Yup.string().trim(),
    position: Yup.string().trim(),
    responsibilities: Yup.string().trim().max(500, "Too long"),
    educName: Yup.string().trim(),
    specialty: Yup.string().trim(),
    certificateName: Yup.string().trim(),
    institution: Yup.string().trim(),
    nameAward: Yup.string().trim(),
    institutionAward: Yup.string().trim(),
    merit: Yup.string().trim().max(500, "Too long"),
    voluntering: Yup.string().trim(),
    obligations: Yup.string().trim().max(500, "Too long"),
    publication: Yup.string().trim(),
    publicationLink: Yup.string().trim(),
    interests: Yup.string().trim().max(500, "Too long"),
  }),
};

export const initialValues = {
    entering: {
        desiredPosition: '',
        phone: '',
        email: '',
        LinkedIn: '',
        professionalSummary: '',
        projectName: '',
        role: '',
        projectLink: '',
        companyName: '',
        position: '',
        responsibilities: '',
        educName: '',
        specialty: '',
        certificateName: '',
        institution: '',
        nameAward: '',
        institutionAward: '',
        merit: '',
        voluntering: '',
        obligations: '',
        publication: '',
        publicationLink: '',
        interests: '',
  },
};
